backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "images"
    label: "画像管理"
    files:
      - file: "content/images.yml"
        label: "カレンダー画像"
        name: "calendar_images"
        fields:
          - label: "カレンダー画像1"
            name: "calendar1"
            widget: "image"
          - label: "カレンダー画像2"
            name: "calendar2"
            widget: "image"
